### ISSUE TITLE
Done with project!

### ISSUE THREAD

**Issue by analins** [analins/game_project#2]
analins.github.io

**Comment by clay-reed-a** [comment]
Ana, 

Beyond brilliant--this was delightful! 

I wish you could've seen the smile on my face while playing it. You would've seen The Delight. 

Now for the fun stuff. 

That is, my questions. :-P 

Would you, could you...

seeing as how the logic in `squareFlipOne` is quite complex...

either...
- Break it up into smaller methods? 
- Somehow make it easier to read? 

Anyhow, huzzah! :cocktail: :hankey: :hotsprings: :atm: :exclamation: 

I think you will really enjoy [SVG](http://snapsvg.io/) and maybe even [things like D3.js](http://d3js.org/). 

Clay a

**Comment by analins** [comment]
Thanks!! I’m glad you liked it!! 

towards the middle/end of the process I started breaking things up more…but for that function I just went with it…and it was like my first major breakthrough when it worked…so then I didn’t want to mess with it…just edited and added a few things here and there. 

I’m sure I could have broken it down…actually one the things I would do differently would have been to keep things smaller, cleaner, and more organized…but for this time I was just happy to get it to work seamlessly even if my code was a little cluttered.

**Comment by clay-reed-a** [comment]
Ana,

I think it's brilliant the way it is. Definite portfolio work. But I do
hope you will return to this project and mess w/ it.

It's good to mess w/ code.

Hey, I thought of a book you might like to read
http://www.oreilly.com/free/badass-making-users-awesome.html.

After I sent my last message.

Clay a
