### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by Avizacherman** [analins/game_project#3]
Ana,

Really impressed with the level of detail that went into this project. I like that you used mockups as a basis for what you were doing then built on top of them. Helps us see your thought process and helps you make sure that you are staying on the path you want.

You seem very comfortable with jQuery based on what I'm seeing in your code. The project itself looks great and functions exactly as you intended. I liked the little champagne animation at the end. 

One thing I am seeing in your code that I would love you to think on is how you can DRY things up a little bit. You repeat little bits of code and while that's not necessarily a bad thing you can probably find ways to simplify it even more. An example of this is your two gameOver functions. Think of a way to reduce this to a single game over function that can take into account whether it was one or two players.

**Comment by analins** [comment]
Thanks!! Yup, for the game over function I could have just had one function with a final condition (else) that would be the outcome if there wasn't a winner variable...so that would have been for the single player. Having cleaner/more organized code was actually me redo in today's standups!

**Comment by Avizacherman** [comment]
No problem. Overall Score 2.5/3 (check the scoring rubric for more details).
